export const COLORS = {
  black: { name: 'Onyx Black', hex: '#121212' },
  white: { name: 'Chalk White', hex: '#F4F2EE' },
  navy: { name: 'Deep Navy', hex: '#1B2430' },
  camel: { name: 'Camel Melange', hex: '#C19A6B' },
  olive: { name: 'Washed Olive', hex: '#4A5340' },
  rose: { name: 'Rose Nude', hex: '#E8B4B8' },
  brown: { name: 'Espresso', hex: '#3A2E2B' },
};

const img = (id) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1000&q=80`;

export const SEED_PRODUCTS = [
  // ---------- CLOTHING ----------
  {
    name: 'Aura Heavyweight Boxy Tee',
    brand: 'Veloura',
    department: 'clothing',
    category: 'T-Shirts',
    gender: 'men',
    price: 75,
    originalPrice: 90,
    discount: 17,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [COLORS.black, COLORS.white, COLORS.olive],
    images: [
      img('photo-1521572267360-ee0c2909d518'),
      img('photo-1583743814966-8936f5b7be1a'),
    ],
    rating: 4.8,
    reviewCount: 42,
    isNew: true,
    isFeatured: true,
    isBestSeller: true,
    stock: 40,
    material: '100% Combed Organic Cotton (280 GSM)',
    fit: 'Boxy oversized',
    description: 'Signature boxy tee with dropped shoulders and a relaxed architectural silhouette.',
  },
  {
    name: 'Classic Oxford Shirt',
    brand: 'Veloura',
    department: 'clothing',
    category: 'Shirts',
    gender: 'men',
    price: 95,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [COLORS.white, COLORS.navy],
    images: [
      img('photo-1602810318383-e386cc2a3ccf'),
      img('photo-1596755094514-f87e34085b2c'),
    ],
    rating: 4.6,
    reviewCount: 30,
    isFeatured: true,
    stock: 35,
    material: '100% Cotton Oxford',
    fit: 'Slim tailored',
    description: 'A crisp tailored Oxford shirt for the modern wardrobe.',
  },
  {
    name: 'Straight Fit Denim Jeans',
    brand: 'Denimworks',
    department: 'clothing',
    category: 'Jeans',
    gender: 'men',
    price: 120,
    sizes: ['30', '32', '34', '36', '38'],
    colors: [COLORS.navy, COLORS.black],
    images: [
      img('photo-1542272604-787c3835535d'),
      img('photo-1541099649105-f69ad21f3246'),
    ],
    rating: 4.5,
    reviewCount: 58,
    isBestSeller: true,
    stock: 50,
    material: 'Stretch Denim',
    fit: 'Straight',
    description: 'Durable straight fit denim built for everyday wear.',
  },
  {
    name: 'Essential Pullover Hoodie',
    brand: 'Veloura',
    department: 'clothing',
    category: 'Hoodies',
    gender: 'unisex',
    price: 85,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [COLORS.black, COLORS.olive, COLORS.camel],
    images: [
      img('photo-1556821840-3a63f95609a7'),
      img('photo-1578587018452-892bacefd3f2'),
    ],
    rating: 4.7,
    reviewCount: 65,
    isNew: true,
    isFeatured: true,
    stock: 60,
    material: 'Cotton Fleece',
    fit: 'Relaxed',
    description: 'Heavyweight fleece hoodie with a relaxed, cocooning fit.',
  },
  {
    name: 'Double-Faced Wool Atelier Coat',
    brand: 'Veloura Atelier',
    department: 'clothing',
    category: 'Coats & Trench',
    gender: 'men',
    price: 385,
    sizes: ['38R', '40R', '42R', '44R'],
    colors: [COLORS.black, COLORS.camel],
    images: [
      img('photo-1544923246-77307dd654cb'),
      img('photo-1539571696357-5a69c17a67c6'),
    ],
    rating: 4.9,
    reviewCount: 18,
    isFeatured: true,
    stock: 12,
    material: 'Double-Faced Wool',
    fit: 'Tailored',
    description: 'A luxurious double-faced wool coat with clean tailored lines.',
  },
  {
    name: 'Siren Column Backless Maxi Dress',
    brand: 'Veloura Atelier',
    department: 'clothing',
    category: 'Dresses & Gowns',
    gender: 'women',
    price: 260,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [COLORS.black],
    images: [
      img('photo-1595777457583-95e059d581b8'),
      img('photo-1566174053879-31528523f8ae'),
    ],
    rating: 4.8,
    reviewCount: 24,
    isFeatured: true,
    isBestSeller: true,
    stock: 15,
    material: 'Silk Blend',
    fit: 'Column silhouette',
    description: 'A sculptural backless column gown for evening occasions.',
  },
  {
    name: 'Mulberry Silk Asymmetric Top',
    brand: 'Veloura Atelier',
    department: 'clothing',
    category: 'Silk & Satin Tops',
    gender: 'women',
    price: 160,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [{ name: 'Champagne Pearl', hex: '#EDE6D6' }],
    images: [
      img('photo-1534528741775-53994a69daeb'),
      img('photo-1515886657613-9f3515b0c78f'),
    ],
    rating: 4.6,
    reviewCount: 20,
    stock: 22,
    material: '100% Mulberry Silk',
    fit: 'Asymmetric relaxed',
    description: 'Fluid mulberry silk top with an asymmetric neckline.',
  },
  {
    name: 'Tailored Wide-Leg Trousers',
    brand: 'Veloura',
    department: 'clothing',
    category: 'Tailored Trousers',
    gender: 'women',
    price: 140,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [COLORS.black, COLORS.navy],
    images: [
      img('photo-1594633312681-425c7b97ccd1'),
      img('photo-1509631179647-0177331693ae'),
    ],
    rating: 4.5,
    reviewCount: 27,
    stock: 30,
    material: 'Wool Blend',
    fit: 'Wide leg',
    description: 'Elegant wide-leg tailored trousers with a fluid drape.',
  },
  {
    name: 'Cashmere Blend Crewneck Knit',
    brand: 'Veloura',
    department: 'clothing',
    category: 'Knitwear & Cashmere',
    gender: 'unisex',
    price: 175,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [COLORS.camel, COLORS.black, COLORS.white],
    images: [
      img('photo-1576871337622-98d48d1cf531'),
      img('photo-1583743814966-8936f5b7be1a'),
    ],
    rating: 4.7,
    reviewCount: 33,
    isNew: true,
    stock: 28,
    material: 'Cashmere Blend',
    fit: 'Regular',
    description: 'Soft cashmere-blend knit for effortless layering.',
  },
  {
    name: 'Structured Blazer',
    brand: 'Veloura',
    department: 'clothing',
    category: 'Blazers & Tailoring',
    gender: 'women',
    price: 220,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [COLORS.black, COLORS.navy],
    images: [
      img('photo-1591047139829-d91aecb6caea'),
      img('photo-1534528741775-53994a69daeb'),
    ],
    rating: 4.6,
    reviewCount: 19,
    isFeatured: true,
    stock: 20,
    material: 'Wool Twill',
    fit: 'Structured',
    description: 'Sharp shoulder-structured blazer for a power silhouette.',
  },

  // ---------- SHOES ----------
  {
    name: 'Runner Pro Sneakers',
    brand: 'Nova Athletic',
    department: 'shoes',
    category: 'Sneakers',
    gender: 'unisex',
    price: 130,
    sizes: ['6', '7', '8', '9', '10', '11'],
    colors: [COLORS.white, COLORS.black],
    images: [
      img('photo-1542291026-7eec264c27ff'),
      img('photo-1595950653106-6c9ebd614d3a'),
    ],
    rating: 4.7,
    reviewCount: 89,
    isBestSeller: true,
    isFeatured: true,
    stock: 70,
    material: 'Mesh & Rubber',
    fit: 'True to size',
    description: 'Lightweight everyday running sneakers with responsive cushioning.',
  },
  {
    name: 'Classic Leather Chelsea Boots',
    brand: 'Heritage & Co.',
    department: 'shoes',
    category: 'Boots',
    gender: 'men',
    price: 210,
    sizes: ['7', '8', '9', '10', '11', '12'],
    colors: [COLORS.brown, COLORS.black],
    images: [
      img('photo-1608256246200-53e635b5b65f'),
      img('photo-1549298916-b41d501d3772'),
    ],
    rating: 4.8,
    reviewCount: 46,
    isFeatured: true,
    stock: 25,
    material: 'Full-Grain Leather',
    fit: 'Regular',
    description: 'Timeless Chelsea boots in full-grain leather with an elastic side panel.',
  },
  {
    name: 'Strappy Heeled Sandals',
    brand: 'Veloura',
    department: 'shoes',
    category: 'Heels',
    gender: 'women',
    price: 165,
    sizes: ['5', '6', '7', '8', '9'],
    colors: [COLORS.black, { name: 'Gold', hex: '#C9A227' }],
    images: [
      img('photo-1543163521-1bf539c55dd2'),
      img('photo-1566174053879-31528523f8ae'),
    ],
    rating: 4.5,
    reviewCount: 31,
    isNew: true,
    stock: 18,
    material: 'Leather',
    fit: 'Regular',
    description: 'Elegant strappy heels finished in soft nappa leather.',
  },
  {
    name: 'Everyday Canvas Slip-Ons',
    brand: 'Nova Athletic',
    department: 'shoes',
    category: 'Casual Shoes',
    gender: 'unisex',
    price: 65,
    sizes: ['6', '7', '8', '9', '10', '11'],
    colors: [COLORS.white, COLORS.navy],
    images: [
      img('photo-1525966222134-fcfa99b8ae77'),
      img('photo-1560769629-975ec94e6a86'),
    ],
    rating: 4.4,
    reviewCount: 52,
    stock: 55,
    material: 'Canvas',
    fit: 'True to size',
    description: 'Easy slip-on canvas shoes for everyday comfort.',
  },

  // ---------- COSMETICS ----------
  {
    name: 'Velvet Matte Lipstick',
    brand: 'Lumière Beauty',
    department: 'cosmetics',
    category: 'Lips',
    gender: 'women',
    price: 28,
    sizes: [],
    colors: [
      { name: 'Rouge Noir', hex: '#8B1E3F' },
      { name: 'Nude Rose', hex: '#C98B83' },
    ],
    images: [
      img('photo-1586495777744-4413f21062fa'),
      img('photo-1596462502278-27bfdc403348'),
    ],
    rating: 4.6,
    reviewCount: 120,
    isBestSeller: true,
    isFeatured: true,
    stock: 100,
    material: 'Vegan Formula',
    fit: '',
    description: 'Long-wear velvet matte lipstick with a weightless, non-drying finish.',
  },
  {
    name: 'Hydrating Foundation SPF 30',
    brand: 'Lumière Beauty',
    department: 'cosmetics',
    category: 'Face',
    gender: 'women',
    price: 42,
    sizes: ['Light', 'Medium', 'Tan', 'Deep'],
    colors: [],
    images: [
      img('photo-1522335789203-aabd1fc54bc9'),
      img('photo-1512496015851-a90fb38ba796'),
    ],
    rating: 4.5,
    reviewCount: 88,
    isNew: true,
    stock: 75,
    material: 'Dermatologist Tested',
    fit: '',
    description: 'Lightweight hydrating foundation with buildable, natural coverage and SPF 30.',
  },
  {
    name: 'Radiance Vitamin C Serum',
    brand: 'Aetherglow',
    department: 'cosmetics',
    category: 'Skincare',
    gender: 'unisex',
    price: 55,
    sizes: [],
    colors: [],
    images: [
      img('photo-1620916566398-39f1143ab7be'),
      img('photo-1608248597359-052495b58399'),
    ],
    rating: 4.8,
    reviewCount: 140,
    isFeatured: true,
    isBestSeller: true,
    stock: 90,
    material: '15% Vitamin C',
    fit: '',
    description: 'Brightening antioxidant serum that evens tone and boosts radiance.',
  },
  {
    name: 'Signature Eau de Parfum',
    brand: 'Aetherglow',
    department: 'cosmetics',
    category: 'Fragrance',
    gender: 'unisex',
    price: 98,
    sizes: ['50ml', '100ml'],
    colors: [],
    images: [
      img('photo-1541643600914-78b084683601'),
      img('photo-1592945403244-b3fbafd7f539'),
    ],
    rating: 4.7,
    reviewCount: 64,
    isNew: true,
    stock: 45,
    material: 'Eau de Parfum',
    fit: '',
    description: 'A warm, woody signature scent with notes of amber and bergamot.',
  },
  {
    name: 'Volumizing Mascara',
    brand: 'Lumière Beauty',
    department: 'cosmetics',
    category: 'Eyes',
    gender: 'women',
    price: 24,
    sizes: [],
    colors: [{ name: 'Blackest Black', hex: '#000000' }],
    images: [
      img('photo-1631730359585-38a4935cbec4'),
      img('photo-1596462502278-27bfdc403348'),
    ],
    rating: 4.4,
    reviewCount: 95,
    stock: 110,
    material: 'Vegan Formula',
    fit: '',
    description: 'Buildable volumizing mascara for dramatic, clump-free lashes.',
  },

  // ---------- ACCESSORIES ----------
  {
    name: 'Leather Crossbody Bag',
    brand: 'Heritage & Co.',
    department: 'accessories',
    category: 'Bags',
    gender: 'women',
    price: 175,
    sizes: [],
    colors: [COLORS.black, COLORS.brown],
    images: [
      img('photo-1584917865442-de89df76afd3'),
      img('photo-1548036328-c9fa89d128fa'),
    ],
    rating: 4.7,
    reviewCount: 41,
    isFeatured: true,
    stock: 22,
    material: 'Full-Grain Leather',
    fit: '',
    description: 'A versatile leather crossbody with a structured silhouette.',
  },
  {
    name: 'Minimalist Analog Watch',
    brand: 'Heritage & Co.',
    department: 'accessories',
    category: 'Watches',
    gender: 'unisex',
    price: 210,
    sizes: [],
    colors: [COLORS.black, { name: 'Silver', hex: '#C0C0C0' }],
    images: [
      img('photo-1524805444758-089113d48a6d'),
      img('photo-1522335789203-aabd1fc54bc9'),
    ],
    rating: 4.6,
    reviewCount: 36,
    isNew: true,
    stock: 30,
    material: 'Stainless Steel',
    fit: '',
    description: 'A clean, minimalist analog watch with a sapphire crystal face.',
  },
  {
    name: 'Polarized Aviator Sunglasses',
    brand: 'Nova Athletic',
    department: 'accessories',
    category: 'Sunglasses',
    gender: 'unisex',
    price: 89,
    sizes: [],
    colors: [COLORS.black],
    images: [
      img('photo-1572635196237-14b3f281503f'),
      img('photo-1511499767150-a48a237f0083'),
    ],
    rating: 4.5,
    reviewCount: 29,
    stock: 40,
    material: 'Polarized Lens',
    fit: '',
    description: 'Classic aviator sunglasses with 100% UV protection.',
  },
];
